# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: 
- xcode9.3
- xcode9.4
- xcode10.0
- xcode10.1
- xcode10.2
language: swift
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- > 
  set -o pipefail && xcodebuild test -enableCodeCoverage YES 
  -workspace Example/ApolloAlamofire.xcworkspace -scheme ApolloAlamofire-Example 
  -sdk iphonesimulator | xcpretty
- pod repo update
- pod lib lint --allow-warnings
